name: "Prepare empty runner"
description: "scale set is an empty runner with nothing installed"

inputs:
  check-kvm:
    description: 'Check if KVM is available'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: "Echo Architecture"
      shell: bash
      run: echo "The architecture of the runner is ${{ runner.os }}-$(uname -m)"

    - name: "Whoami"
      shell: bash
      run: whoami

    - name: Check if KVM is available with kvm-ok
      if: ${{ inputs.check-kvm == 'true' }}
      shell: bash
      run: kvm-ok

    - name: Check LFS usages
      shell: bash
      run: git lfs fsck

    - name: Check disk space
      shell: bash
      run: df -h

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Setup Android SDK
      uses: premex-ab/setup-android@v3.2.2
      with:
        cmdline-tools-version: 11076708