name: "Prepare empty runner"
description: "scale set is an empty runner with nothing installed"

inputs:
  check-kvm:
    description: 'Check if KVM is available'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: "Echo Architecture"
      shell: bash
      run: echo "The architecture of the runner is ${{ runner.os }}-$(uname -m)"

    - name: "Whoami"
      shell: bash
      run: whoami

    - name: "party"
      shell: bash
      run: cat /shared/fest.txt

    - name: "RUNTIME_ARCH"
      shell: bash
      run: echo $RUNTIME_ARCH

    - name: Check if KVM is available with kvm-ok
      if: ${{ inputs.check-kvm == 'true' }}
      shell: bash
      run: kvm-ok

    #- name: "ls kvm"
    #  shell: bash
    #  run: ls -al /dev/kvm

    - name: Check LFS usages
      shell: bash
      run: git lfs fsck

    - name: Check disk space
      shell: bash
      run: df -h

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Setup Android SDK
      uses: premex-ab/setup-android@v4
      with:
        cmdline-tools-version: 12266719
        packages: 'platform-tools'